language: ruby
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - 2.2.2
#   - rbx-19mode
#  - 1.8.7
#  - jruby-18mode # JRuby in 1.8 mode
#  - rbx-18mode

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
